export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
//
export const LOADING_START = 'LOADING_START'
export const LOADING_STOP = 'LOADING_STOP'
//
export const TOAST_MESSAGE_SUCCESS = 'TOAST_MESSAGE_SUCCESS'
export const TOAST_MESSAGE_FAILURE = 'TOAST_MESSAGE_FAILURE'
export const TOAST_MESSAGE_INFO = 'TOAST_MESSAGE_INFO'
export const TOAST_MESSAGE_WARNING = 'TOAST_MESSAGE_WARNING'
